pipeline {
    agent any

    stages {

        stage('Build container') {
            steps {
                sh 'cd fasapi && docker build -t fastapiapp:v1 .'
            }
        }

        stage('Load Image into MiniKube') {
            steps {
                sh 'minikube image load fastapiapp:v1'
            }
        }

        stage('Deploy image to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
                sh 'kubectl apply -f service.yaml'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods'
                sh 'kubectl get svc'
            }
        }
    }
}